---
title: "Introduction to Psychological Statistics"
subtitle: "Understanding People Through Data"
author: "A.D.Perez, PhD"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
output:
  bookdown::gitbook:
    css: "style.css"
    config:
      toc:
        collapse: section
        before: <p class="toc-title">Table of Contents</p>
        after: |
          <p>Please see the <a href="https://bookdown.org">bookdown documentation</a> for more information.</p>
---

<div class="foreword">
# Welcome to the Online Book for Psychological Statistics {.unnumbered}

## Understanding People Through Data

This online textbook serves as a fundamental guide and companion for students venturing into the scientific study of people through statistics and probability. It is designed to accompany our course, which introduces essential statistical concepts and tools needed to understand and conduct psychological research.

## What You Will Learn

The content of this book spans several key topics:

-   **Descriptive Statistics:** Learn how to collect, summarize, and present data effectively.
-   **Linear Regression:** Understand the relationship between variables and how to predict outcomes.
-   **Design of Experiments:** Explore how experiments are structured to test hypotheses and examine cause and effect.
-   **Introductory Probability:** Gain insights into the likelihood and patterns of events.
-   **Random Variables, Normal Distribution, and T-Distribution:** Delve into the behaviors of data under different conditions and understand the foundational distributions in statistics.
-   **Statistical Inference:** Master the techniques for making conclusions about a population based on sample data, including confidence intervals and significance tests.

## Emphasis on Psychological Research

This book emphasizes methods commonly used by psychologists to:

-   Collect and describe data.
-   Graph and interpret patterns in data concerning human behavior and interactions.
-   Report research findings effectively in research papers.

Throughout this text, real-world examples, case studies, and datasets specific to psychological research will be used to illustrate how statistical tools can provide insights into complex human behaviors and relationships.

## Hands-On Learning with R and R Studio

-   Each chapter includes practical R code examples and exercises that require you to analyze data and interpret results using R and R Studio. This hands-on approach ensures that you not only learn the theoretical aspects of statistics but also acquire the skills to implement these techniques effectively.

Whether you are a student of psychology or a budding researcher, this book will equip you with the statistical understanding and tools necessary to excel in your studies and future careers. Dive into the fascinating world of psychological statistics and discover how data can reveal insights about human nature!
</div>
